### ISSUE TITLE
jQuery Dependency 1.10.2

### ISSUE THREAD

**Issue by 58bits** [markgoodyear/scrollup#37]
Thanks for the excellent plugin.

Does scrollup really have a fixed dependency on jQuery 1.10.2? I've installed scrollup via bower and am using jQuery ~2.1.1 on the project and bower is forcing us to choose between meeting the scrollup dependency, and our desire to use a later version of jQuery. Are we missing something? Or is there any chance you could semver this to a higher version of jQuery?

**Comment by pederan** [comment]
+1

**Comment by markgoodyear** [comment]
Apologies on the slow response on this issue!

I've updated the bower config and it should now be greater or equal to 1.10.2, rather than fixed. Could you confirm if this has fixed the issue?

**Comment by pederan** [comment]
Hi, thanks. But this is not working since jQuery v 1.10.2's bower file is missing the ignore entry (https://github.com/jquery/jquery/blob/16b079b164d62bd807c612806842a13bf9b04d17/bower.json). Getting this error when installing via bower: bower jquery#1.10.2       invalid-meta jquery is missing "ignore" entry in bower.json

Can you require greater or equal to 1.11.0 since v 1.11.0 seems to have a valid bower file?

**Comment by markgoodyear** [comment]
I've bumped the version now, hopefully this one will work! :)

**Comment by pederan** [comment]
You also have to update the bower registry. Bump plugin version in bower.json and package.json, eg 2.4.1, and git tag it with the new version, see Updating and Maintanance section here: http://bob.yexley.net/creating-and-maintaining-your-own-bower-package/

Thanks!

**Comment by markgoodyear** [comment]
Done! Let me know if this is working now.

**Comment by pederan** [comment]
You forgot to change the version in bower.json so unfortunately it is not fixed. Just edit to 2.4.1 and I think that will do it.

**Comment by markgoodyear** [comment]
Wow, I don't think I could have done a worse job! This is now pushed, and thanks for the patience!

**Comment by 58bits** [comment]
Thanks Mark!
